# Step 1: Nginx 기반 이미지 사용
FROM nginx:alpine

# Step 2: 프로젝트의 정적 파일을 Nginx 기본 경로로 복사
COPY . /usr/share/nginx/html

# Step 3: Nginx 설정 파일을 복사
COPY nginx.conf /etc/nginx/nginx.conf

# Step 4: Nginx 시작
CMD ["nginx", "-g", "daemon off;"]
